export const votingV2Abi = [
  {
    type: 'function',
    name: 'commitAndEmitEncryptedVote',
    inputs: [
      { name: 'identifier', type: 'bytes32', internalType: 'bytes32' },
      { name: 'time', type: 'uint256', internalType: 'uint256' },
      { name: 'ancillaryData', type: 'bytes', internalType: 'bytes' },
      { name: 'hash', type: 'bytes32', internalType: 'bytes32' },
      { name: 'encryptedVote', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'executeUnstake',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getCurrentRoundId',
    inputs: [],
    outputs: [{ name: '', type: 'uint32', internalType: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPendingRequests',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'tuple[]',
        internalType: 'struct VotingV2Interface.PendingRequestAncillaryAugmented[]',
        components: [
          { name: 'lastVotingRound', type: 'uint32', internalType: 'uint32' },
          { name: 'isGovernance', type: 'bool', internalType: 'bool' },
          { name: 'time', type: 'uint64', internalType: 'uint64' },
          { name: 'rollCount', type: 'uint32', internalType: 'uint32' },
          { name: 'identifier', type: 'bytes32', internalType: 'bytes32' },
          { name: 'ancillaryData', type: 'bytes', internalType: 'bytes' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getRoundEndTime',
    inputs: [{ name: 'roundId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getVotePhase',
    inputs: [],
    outputs: [{ name: '', type: 'uint8', internalType: 'enum VotingV2Interface.Phase' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getVoterFromDelegate',
    inputs: [{ name: 'caller', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'gat',
    inputs: [],
    outputs: [{ name: '', type: 'uint128', internalType: 'uint128' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getVoterStakePostUpdate',
    inputs: [{ name: 'voter', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint128', internalType: 'uint128' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'outstandingRewards',
    inputs: [{ name: 'voter', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'processResolvablePriceRequests',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'requestUnstake',
    inputs: [{ name: 'amount', type: 'uint128', internalType: 'uint128' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'revealVote',
    inputs: [
      { name: 'identifier', type: 'bytes32', internalType: 'bytes32' },
      { name: 'time', type: 'uint256', internalType: 'uint256' },
      { name: 'price', type: 'int256', internalType: 'int256' },
      { name: 'ancillaryData', type: 'bytes', internalType: 'bytes' },
      { name: 'salt', type: 'int256', internalType: 'int256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'stake',
    inputs: [{ name: 'amount', type: 'uint128', internalType: 'uint128' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'unstakeCoolDown',
    inputs: [],
    outputs: [{ name: '', type: 'uint64', internalType: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'voterStakes',
    inputs: [{ name: '', type: 'address', internalType: 'address' }],
    outputs: [
      { name: 'stake', type: 'uint128', internalType: 'uint128' },
      { name: 'pendingUnstake', type: 'uint128', internalType: 'uint128' },
      { name: 'rewardsPaidPerToken', type: 'uint128', internalType: 'uint128' },
      { name: 'outstandingRewards', type: 'uint128', internalType: 'uint128' },
      { name: 'unappliedSlash', type: 'int128', internalType: 'int128' },
      { name: 'nextIndexToProcess', type: 'uint64', internalType: 'uint64' },
      { name: 'unstakeTime', type: 'uint64', internalType: 'uint64' },
      { name: 'delegate', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'votingToken',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract ExpandedIERC20' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'withdrawAndRestake',
    inputs: [],
    outputs: [{ name: '', type: 'uint128', internalType: 'uint128' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdrawRewards',
    inputs: [],
    outputs: [{ name: '', type: 'uint128', internalType: 'uint128' }],
    stateMutability: 'nonpayable',
  },
] as const
